### ISSUE TITLE
Semantic Ontology building from Video Action Recognition

### ISSUE THREAD

**Issue by SinDongHwan** [gsig/temporal-fields#7]
![ontologybuilding](https://user-images.githubusercontent.com/30520896/30793976-77846acc-a200-11e7-8912-58c540ae944b.png)

Dear Gunnar,
As I asked you earlier, I am still struggling to extract the relationship of objects from a simple action video from your Temporal-fields program.
After a week of work, I doubt the possibility of extract more information than you've pre-trained (i.e., 157 categories, 38 objects, 33 actions, 15 scenes) such as location and/or relation of the objects (i.e., x, y points or "is under", "is on", "is behind" ...) as shown on the attached figure which assumes a snapshot of a video. Correct?
If I prepare learning video and categorize them properly, then I can extract static objects such as "person", "tree", "grass", "water", "island, "mountain", "clouds", but still, I cannot extract information of the predicate of a triple in RDF, from your temporal-fields, right ?

Donghwan.

**Comment by gsig** [comment]
Hi Donghwan,

Extracting spatial relationships between objects ("is under" etc) is not modeled in this work. For each frame, we predict a tensor for categories,objects,verbs etc, and do so over time. This tensor can be used to extract _temporal_ relationships, but there is no spatial modelling in the code. Our work focuses on actions, and our interest in objects is just the objects that are parts of the actions. In theory you could try to distill the location of the object from the frame but it will likely be involved.

The problem is that there are not many datasets that provide full scene parsing of every frame of a video like the figure shows, and the key problem is adapting image models to videos. 

Since you are interested in extracting relationships, it is possible that even borrowing image models and running them on videos with extensive post-processing could work. (temporal smoothing, only top relationships, etc) 

Hope that helps,
Gunnar

**Comment by SinDongHwan** [comment]
Yes, I do agree with your comments.
_Since you are interested in extracting relationships, it is possible that even borrowing image models and running them on videos with extensive post-processing could work. (temporal smoothing, only top relationships, etc)_
I do not have enough background to do the work but I will keep study on this.
Thank you very much, Gunnar.
Donghwan.
